// Short link redirects - edit this to add/remove redirects
export const redirects: Record<string, string> = {
  github: "https://github.com/lamngockhuong",
  gh: "https://github.com/lamngockhuong",
  linkedin: "https://linkedin.com/in/lamngockhuong",
  li: "https://linkedin.com/in/lamngockhuong",
  twitter: "https://x.com/lamngockhuong",
  x: "https://x.com/lamngockhuong",
  email: "mailto:hi@khuong.dev",
  mail: "mailto:hi@khuong.dev",
  blog: "https://dev.ngockhuong.com",
  dev: "https://khuong.dev",
  cv: "https://khuong.dev/cv",
  resume: "https://khuong.dev/cv",
  facebook: "https://facebook.com/lamngockhuong",
  fb: "https://facebook.com/lamngockhuong",
  instagram: "https://instagram.com/lamngockhuong",
  ig: "https://instagram.com/lamngockhuong",
  youtube: "https://youtube.com/@lamngockhuong",
  yt: "https://youtube.com/@lamngockhuong",
  telegram: "https://t.me/lamngockhuong",
  tg: "https://t.me/lamngockhuong",
  strava: "https://www.strava.com/athletes/lamngockhuong",
};
